version: '3.5'

services:
  app1: &app
    build: .
    hostname: app1
    environment:
      DB_URL: "postgres://postgres:12345678@postgres:5432/postgres"
    expose:
      - "8080"
    # depends_on:
    #   - postgres
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.6GB'
  app2:
    <<: *app
    hostname: app2

  # postgres:
  #   image: postgres
  #   command: postgres -c 'max_connections=450' -c 'log_error_verbosity=terse'
  #   environment:
  #     POSTGRES_DB: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 12345678
  #   ports:
  #     - 5432:5432
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 20
  #     start_period: 10s
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.6'
  #         memory: '1.5GB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
    - ${PWD}/nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - app1
      - app2
    ports:
      - '9999:9999'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.3GB'